add pcm_prepare before pcm_start
tinyalsa/tinyalsa pull request #206
Opened 2021-05-19 07:37 UTC by dvdli

For the compatibility with version 1.x, do pcm_prepare before starting the pcm driver.

2021-05-19 11:48 UTC, dvdli commented
@tay10r @simonrules @gkasten Could you please help to review this patch set?

2021-05-22 20:01 UTC, tay10r requested changes

2021-05-23 11:06 UTC, dvdli commented on src/mixer.c
> -        if ((value < mixer_ctl_get_range_min(ctl)) ||
I found that there are some drivers set the maximum of the control as UINT_MAX and the minimum as 0, but the max/min are stored in signed integers. Therefore, the range is 0 -> -1. 

I think not checking values in tinyalsa and checking these in drivers are better.

2021-05-24 13:44 UTC, tay10r commented on src/mixer.c
> -        if ((value < mixer_ctl_get_range_min(ctl)) ||
I see. I wonder how this affects user interfaces that use the range min and max to map the input range. In a spin box for example, or a slider bar. Not that this is an issue above, but I wonder if that's a separate issue that needs to be addressed.

2021-05-24 13:45 UTC, tay10r approved these changes

2021-05-26 03:37 UTC, dvdli commented on src/mixer.c
> -        if ((value < mixer_ctl_get_range_min(ctl)) ||
In my opinion, users still can trust almost every range of mixer control and get the min and max by the APIs mixer_ctl_get_range_min and mixer_ctl_get_range_max. Therefore, for the cases like a spin box or a slider bar, they still can work. We just let the driver to take the responsibility to check the range.

Note: tinyalsa also doesn't check the range in the `mixer_ctl_set_array`

2021-05-26 03:38 UTC, merged